excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Carthage
  - Pods
  
disabled_rules: # rule identifiers to exclude from running
  - force_cast  
  - identifier_name
  - trailing_whitespace

# configurable rules can be customized from this configuration file
# binary rules can set their severity level
# identifier_name:
#   severity: warning # warning
#   min_length: 1 # only warning
#   max_length: 80 # warning 
line_length: 150