# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'
use_frameworks!

def shared_pods
  pod 'RxSwift', '~> 5.1.1'
  pod 'RxCocoa', '~> 5.1.1'
  pod 'Alamofire', '~> 5.4.0'
  pod 'Localize'  
  pod 'NVActivityIndicatorView'
  pod 'SwiftLint'
  pod 'Kingfisher'
  pod 'IQKeyboardManagerSwift'
  pod 'GoogleSignIn'
  pod 'FBSDKLoginKit'
end

target 'SwiftSourceBase' do
  # Pods for SwiftSourceBase
  shared_pods
end

target 'DevSwiftSourceBase' do
  # Pods for SwiftSourceBase
  shared_pods
end

target 'StgSwiftSourceBase' do
  # Pods for SwiftSourceBase
  shared_pods
end

