# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
use_frameworks!

def shared_pods
  pod 'RxSwift', '~> 5'
  pod 'RxCocoa', '~> 5'
  pod 'Alamofire'
  pod 'Localize', '~> 2.3.0'  
  pod 'NVActivityIndicatorView'
  pod 'SwiftLint'
end

target 'SwiftSourceBase' do
  # Pods for SwiftSourceBase
  shared_pods
end

target 'DevSwiftSourceBase' do
  # Pods for SwiftSourceBase
  shared_pods
end

target 'StgSwiftSourceBase' do
  # Pods for SwiftSourceBase
  shared_pods
end

